INSERT INTO SOLDIERS(FIRSTNAME, LASTNAME, RANK ) VALUES ('Andrzej', 'Gołota', 'mar.')
INSERT INTO SOLDIERS(FIRSTNAME, LASTNAME, RANK ) VALUES ('Stefan', 'Eloł', 'st. mar.')
INSERT INTO KBKAK( "NR", "ROK") VALUES ('NN45872', '1982')
INSERT INTO KBKAK( "NR", "ROK") VALUES ('NN45873', '1981')